### ISSUE TITLE
Bad request 403 forbidden

### ISSUE THREAD

**Issue by iamtorsten** [Kimmax/SYMMExtractor#2]
Decrypted videos can't be downloaded anymore. VideoDownloader throws.

Example url https://www.youtube.com/watch?v=OPARVXqrbWc

**Comment by Kimmax** [comment]
The Decipher function has changed. Im looking into it

**Comment by iamtorsten** [comment]
Ok ... Kannst du mich informieren?

Von meinem iPhone gesendet

**Comment by Kimmax** [comment]
Fixed

**Comment by iamtorsten** [comment]
Thx 😊

Von meinem iPhone gesendet
