### ISSUE TITLE
Audio extracting throws System.InvalidOperationException

### ISSUE THREAD

**Issue by Robbertie** [Kimmax/SYMMExtractor#3]
Hi dude,

I just started using your version of the extractor but it throws the same one as the other one did:
System.InvalidOperationException
It can't find any video where it can extract the audio from I think.

**Comment by Kimmax** [comment]
Can you pass me a non working link please?

**Comment by Robbertie** [comment]
Okay it was my fault I have it working now.. Only need to convert it to MP3 since it downloads the aac.

**Comment by Robbertie** [comment]
Nvm it works now thanks a lot for this fork <3

**Comment by Kimmax** [comment]
Actually you can pass the output format as the third parameter to the [`AudioDownloader`](https://github.com/Kimmax/SYMMExtractor/blob/master/YoutubeExtractor/YoutubeExtractor/AudioDownloader.cs#L44). Let me know if the conversation is not done correctly, so I can fix it.
