### ISSUE TITLE
Faster way to get the youtube video downloadURL?

### ISSUE THREAD

**Issue by Robbertie** [Kimmax/SYMMExtractor#4]
Hi,

Is there any faster way to get the audio url of the video because I stream the audio and it still takes quite a long time before it starts streaming the audio.

**Comment by Robbertie** [comment]
Nevermind find a way to do it 👍

**Comment by Kimmax** [comment]
Would you mind sharing this? Would love to improve this
Actually didn't even knew that someone is actually using this >D

**Comment by Robbertie** [comment]
Well what I needed was to get the Google video link. I used this library before to download the audio  but now I stream it instead with Naudio.  I am using libvideo now instead. Because it is way faster

**Comment by Kimmax** [comment]
Thanks, will consider implementing libvideo (y)
This lib is able to stream the link (also using Naudio) too btw

**Comment by Robbertie** [comment]
Yeah that's how I found out about the audio streaming so thanks a lot for that. I just found that libvideo gets the url quicker so I use that instead
